### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by a601942905git** [sail-y/eshop-cache#1]
您好，看了你的博客文章，有些疑问，希望可以得到您本人的回答。
1.关于在分发层通过一致hash的方式来分发到指定的nginx应用层面，这个地方看到后端应用层nginx的ip地址是写死的2个，如果添加服务器是不是只能通过修改lua脚本来实现。添加了机器，那么之前2台应用层nginx的本地缓存就没用了，该怎么处理。
2.既然使用到了缓存服务器的本地缓存，那么应用层的nginx也应该采用一直hash的算法，让请求路由到指定的后端服务器上面去。既然是这样，那么只会存在同一时间多个请求打在同一台缓存服务器上，应该只需要加本地锁来防止多个请求同时请求后端商品服务，不太需要分布式锁吧？
3.关于lua脚本的开发，有没有好的开发工具？商品详情页面应该是个很复杂的页面，如果只是在linux服务器下面通过vi命令来编辑，出错的概率大，排查问题也不方便。

**Comment by sail-y** [comment]
你好，这些文章并非我原创，是我看视频整理后的课程笔记，不过关于你的问题我试着交流一下

1. nginx的本地缓存时间并不长，采用一致性hash算法，hash后到不同机器的key变化是少数，而且后面还有一层redis缓存做防护
2. 笔记里的应用层并没有用到hash算法，在实际生产环境中，应用层分发到的机器可能只是一个网关服务器，会被二次负载均衡，最终访问的后端服务器并不确定是哪一台
3. 关于lua和openresty的开发，建议参考开涛的博客：http://jinnianshilongnian.iteye.com/blog/2190344
