### ISSUE TITLE
关于缓存预热的问题

### ISSUE THREAD

**Issue by SupNewBeen** [sail-y/eshop-cache#2]
石杉老师在课程里是说，如果系统刚上线的时候，redis里面没有数据，为了防止大量的请求直接打到MySQL上，那么就需要根据当天的具体访问情况，实时统计出访问频率较高的热数据。

但是我有一个问题，既然是系统刚上线，那么又何来“当天的访问情况”呢？如果已经有了“当天的访问情况”，那么系统肯定已经运行了一段时间了吧，为什么又需要缓存预热呢？

此外，石杉老师说，在redis宕机重新启动的情况下，也会出现redis为空的情况。可是真的会这样吗，redis开启了AOF和RDB还会出现重启之后数据丢失的情况吗？

以上是我个人在学习过程中的一点问题哈，想和大家讨论一下

**Comment by sail-y** [comment]
我的理解是这个地方主要是对新启动的服务，JVM层的缓存进行预热。就像你说的，这些数据一直都在访问，也在做统计，那么redis里肯定是有的。但是系统启动后，JVM里是没有的，如果redis挂了，那么所有的请求都会到mysql了，应该是这样。


第二个问题，我记不太清了，我感觉应该没有
